#data_list: ['MPQA', 'SST2', 'Subj', 'TREC', 'MR', 'CustomReview']
dirname: ../data
# 两个保证有一个有embedding文件就好
embedding_path: ['../../../opt/embeddings/GoogleNews-vectors-negative300.txt',
                 '../data/embeddings/GoogleNews-vectors-negative300.bin']
datatype:
  binary: ['MR', 'Subj']
  train_test: ['SST2','SU','SU1','SU2']
data_list:
  MR:
    pos: mr.pos
    neg: mr.neg
  SST2:
    train: stsa.binary.train
    test: stsa.binary.test
    dev: stsa.binary.dev
  SU:
    train: startup.binary.train
    test: startup.binary.test
    dev: startup.binary.dev
  SU1:
    train: startup001.binary.train
    test: startup001.binary.test
    dev: startup001.binary.dev
  SU2:
    train: startup2.binary.train
    test: startup2.binary.test
    dev: startup2.binary.dev
  Subj:
    pos: subj.subjective
    neg: obj.objective
  TREC:
    train: TREC.train
    test: TREC.test
  CustomReview:
    pos: custrev.pos
    neg: custrev.neg
  MPQA:
    pos: mpqa.pos
    neg: mpqa.neg
seed: 12
valid_rate: 0.2
res_path: ../data/embeddings/{}.pkl
best_model_path: ../data/save
cuda_index: 0
output_channels: 100
max_length: 100
batch_size: 100
epoch_size: 100
lr: 0.0005
patience: 10
l2: 1e-5
max_grad_norm: 3.0
esp: 1e-5
kfold: 10
dropout: 0.5
filters: [3, 4, 5]

# train_mode: ['random', 'static', 'fine-tuned']
use_pretrained: False
train_mode: 'random'
emb_dim: 10